# ==============================================================================
# Script: Entra ID User Provisioning Automation
# Description: Automates the creation of foundational enterprise users 
#              for a simulated environment using Microsoft Graph.
#
# SECURITY & COMPLIANCE NOTE: 
# All user identities, names, and attributes generated by this script are 
# ENTIRELY FICTIONAL and mirror standard Microsoft Contoso lab templates. 
# NO real Personally Identifiable Information (PII) is used or exposed.
# ==============================================================================

# 1. Connect to Microsoft Entra ID
Connect-MgGraph -Scopes "User.ReadWrite.All", "Directory.ReadWrite.All"

# 2. Define the default password for new users
$PasswordProfile = @{
    Password = "TemporaryPassword2026!"
    ForceChangePasswordNextSignIn = $true
}

# 3. Define the domain (Update this with your trial domain before running)
$Domain = "@jordanstoddcloud.onmicrosoft.com"

# ==============================================================================
# 4. Provision Fictional Test Users
# ==============================================================================

Write-Host "Provisioning User: Alex Wilber (Cloud Operations)" -ForegroundColor Cyan
New-MgUser -DisplayName "Alex Wilber" `
           -GivenName "Alex" `
           -Surname "Wilber" `
           -UserPrincipalName "awilber$Domain" `
           -MailNickname "awilber" `
           -JobTitle "Cloud Administrator" `
           -Department "Cloud Operations" `
           -UsageLocation "US" `
           -AccountEnabled:$true `
           -PasswordProfile $PasswordProfile

Write-Host "Provisioning User: Megan Bowen (Finance)" -ForegroundColor Cyan
New-MgUser -DisplayName "Megan Bowen" `
           -GivenName "Megan" `
           -Surname "Bowen" `
           -UserPrincipalName "mbowen$Domain" `
           -MailNickname "mbowen" `
           -JobTitle "Financial Controller" `
           -Department "Finance" `
           -UsageLocation "US" `
           -AccountEnabled:$true `
           -PasswordProfile $PasswordProfile

Write-Host "Provisioning User: Lynne Robbins (Sales)" -ForegroundColor Cyan
New-MgUser -DisplayName "Lynne Robbins" `
           -GivenName "Lynne" `
           -Surname "Robbins" `
           -UserPrincipalName "lrobbins$Domain" `
           -MailNickname "lrobbins" `
           -JobTitle "Account Executive" `
           -Department "Sales" `
           -UsageLocation "US" `
           -AccountEnabled:$true `
           -PasswordProfile $PasswordProfile

Write-Host "Fictional user provisioning completed successfully!" -ForegroundColor Green